# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arriving' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Mapbox-iOS-SDK', '~> 3.6'
    pod 'MapboxDirections.swift'
    pod 'AlamofireSwiftyJSON'
    pod 'PromiseKit/Alamofire'
    pod 'Localize-Swift', '~> 2.0'
end
